/**
 * AI Provider and Model Types
 */

export enum AI_PROVIDER {
  OPENAI = 'OPENAI',
}

export enum AI_MODEL {
  GPT_4O = 'gpt-4o',
  GPT_4O_MINI = 'gpt-4o-mini',
}

export enum AI_TASK {
  AGE_RANGE_ESTIMATION = 'AGE_RANGE_ESTIMATION',
  ALIAS_INFERENCE = 'ALIAS_INFERENCE',
  TEXT_SUMMARIZATION = 'TEXT_SUMMARIZATION',
  ENTITY_EXTRACTION = 'ENTITY_EXTRACTION',
  EMAIL_PATTERN_INFERENCE = 'EMAIL_PATTERN_INFERENCE',
  PROFILE_PHOTO_CONFIDENCE_SIGNAL = 'PROFILE_PHOTO_CONFIDENCE_SIGNAL',
  BIO_EVOLUTION_ANALYSIS = 'BIO_EVOLUTION_ANALYSIS',
  DOMAIN_OWNERSHIP_INFERENCE = 'DOMAIN_OWNERSHIP_INFERENCE',
  POSTS_CHUNK_EVIDENCE_EXTRACTION = 'POSTS_CHUNK_EVIDENCE_EXTRACTION',
  DECISION_MAKER_BRAND = 'DECISION_MAKER_BRAND',
  REVENUE_SIGNAL_INFERENCE = 'REVENUE_SIGNAL_INFERENCE',
  LINKEDIN_ACTIVITY_INFERENCE = 'LINKEDIN_ACTIVITY_INFERENCE',
  COMPETITOR_MENTIONS_EXTRACTION = 'COMPETITOR_MENTIONS_EXTRACTION',
  HIRING_SIGNALS_EXTRACTION = 'HIRING_SIGNALS_EXTRACTION',
  TOPIC_THEMES_INFERENCE = 'TOPIC_THEMES_INFERENCE',
  TONE_SIGNALS_INFERENCE = 'TONE_SIGNALS_INFERENCE',
  COLLEAGUE_NETWORK_INFERENCE = 'COLLEAGUE_NETWORK_INFERENCE',
  EXTERNAL_SOCIALS_EXTRACTION = 'EXTERNAL_SOCIALS_EXTRACTION',
  EVENT_ATTENDANCE_EXTRACTION = 'EVENT_ATTENDANCE_EXTRACTION',
  LOW_QUALITY_ENGAGEMENT_EXTRACTION = 'LOW_QUALITY_ENGAGEMENT_EXTRACTION',
  DESIGN_HELP_SIGNALS_EXTRACTION = 'DESIGN_HELP_SIGNALS_EXTRACTION',
  FINAL_SUMMARY_INFERENCE = 'FINAL_SUMMARY_INFERENCE',
  FLOW_FILTER = 'FLOW_FILTER',
}
