export const EventTypes = {
  PING: 'Ping',
  PONG: 'Pong',
  NEW_PINGER: 'NewPinger',
};

export const TransactionTypes = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  SETTLING: 'SETTLING',
  SETTLEMENT: 'SETTLEMENT',
  PARTICIPATION: 'PARTICIPATION',
  SIDE_WAGER: 'SIDE_WAGER',
  REFUND: 'REFUND',
  JOIN_CHALLANGE: 'PARTICIPATION_EVENT',
};

export enum EVENT_TYPE {
  PING = 'PING',
  PONG = 'PONG',
  NEW_PINGER = 'NEW_PINGER',
}
